variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0  

include:
  - local: /.gitlab/build-astra.yml
  - local: /.gitlab/build-windows.yml
  - local: /.gitlab/integration-test-astra.yml
    needs: 
      stages: ['build']
  - local: /.gitlab/doxygen.yml
  - local: /.gitlab/install.yml

