variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0

stages: 
  - build
  - publish

linux:
  stage: build
  tags: [alse]
  script: 
    - conan install . -b "missing"
    - cmake . -G Ninja -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
    - cmake --build build/Release --config Release

  artifacts:
    paths:
      - build/Debug
    expire_in: 1 hour

windows:
  stage: build
  tags: [windows-arch]
  script:
    - puff install . --fresh --os windows
    - x86_64-w64-mingw32-cmake -S . -B target-windows-x86_64-static -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=./dependencies -DBUILD_SHARED_LIBS=OFF -DMINGW_ADDITIONAL_LIBDIR=./dependencies
    - cmake --build target-windows-x86_64-static --config Release
    - cmake --install target-windows-x86_64-static --prefix target-windows-x86_64-static/export
    - cp -r .puff target-windows-x86_64-static/export/.puff
    - cp Puff.toml target-windows-x86_64-static/export/Puff.toml

  artifacts:
    paths:
      - target-windows-x86_64-static/export
    expire_in: 1 hour

publish:
  stage: publish
  tags: [alse]
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: manual
  needs:
    - job: linux
      artifacts: false
    - job: windows
      artifacts: false
  script:
    - echo "Publishing to conan repo"

