---
stages:
  - build
  - test
  - publish

include:
  - project: "developers/v2/libs/essentials/ci"
    ref: main
    file:
      - 'linux/conan.yml'
      - 'utils/variables.yml'

local_variables:
  extends: .variables_core_job
  script:
    - !reference [.svariables, conan_project_name]

build:alse:
  stage: build
  extends: .build_extend
  artifacts:
    paths:
      - build/Release

test:alse:
  stage: test
  allow_failure: true
  extends: .tests_catch2_extend

publish:alse:
  stage: publish
  extends: .publish_extend

deploy:alse:
  tags: [alse]
  stage: publish
  needs:
    - job: build:alse
      artifacts: true
  # extends: .deploy_extend
  script:
    - echo "Collecting binary package..."
    - ls
  artifacts:
    name: $CI_PROJECT_TITLE-$CI_COMMIT_REF_NAME-$CI_JOB_NAME
    paths: [./build/Release/export]


documentation:
  tags: [dev-utils]
  stage: publish
  allow_failure: true
  needs:
    - job: test:alse
  before_script:
    - git clone https://github.com/maybe-unused/m.css.git
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install jinja2 pygments
  script:
    - python3 m.css/documentation/doxygen.py ./conf.py
    - echo "Deploying to GitLab Pages..."
    - mkdir -p public
    - cp -r docs/* public
  artifacts:
    paths:
      - public
