variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0  


stages: 
  - test
  - build
  - poppy

test:
  stage: test
  tags: [alse]
  script: 
    - echo $ARTIFACTORY_KEY
    - echo $ARTIFACTORY_REFERENCE_KEY
    - echo $ARTIFACTORY_USER

include:
  - project: 'test/essentials/ci'
    ref: main
    file: 'poppy/poppy.yml'
    inputs:
      build_windows_static: 'true'
      build_alse_static: 'true'


