---
stages:
  - build
  - test
  - publish

include:
  - project: "developers/v2/libs/essentials/ci"
    ref: main
    file:
      - 'linux/conan.yml'
      - 'utils/variables.yml'

local_variables:
  extends: .variables_core_job
  script:
    - !reference [.svariables, conan_project_name]

build:alse:
  stage: build
  extends: .build_extend

test:alse:
 stage: test
 allow_failure: true
 extends: .tests_extend
 script:
   - conan build . -b "missing" -o "$CONAN_PACKAGE_NAME/*:test=True"
   - ./build/Release/tests/$CONAN_PACKAGE_NAME-test --gtest_color=yes --gtest_output=xml --gtest_shuffle --gtest_repeat=1 --platform=linuxfb

publish:alse:
  stage: publish
  extends: .publish_extend
