variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0  

stages:
  - poppy-generate
  - poppy-upload

  - build
  - integration-test
  - install
  - documentation
  
  
include:
  - project: 'test/essentials/ci'
    ref: main
    file: 'poppy/any-src-artifacts.yml'

  - project: 'test/essentials/ci'
    ref: main
    file: 'poppy/alse-static-artifacts.yml'

  - project: 'test/essentials/ci'
    ref: main
    file: 'poppy/windows-static-artifacts.yml'

  - project: 'test/essentials/ci'
    ref: main
    file: 'poppy/upload-artifactory.yml'


  - local: /.gitlab/build-astra.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "trigger-install-windows"
        when: never
      - when: always
  - local: /.gitlab/build-windows.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "trigger-install-alse"
        when: never
      - when: always


  - project: 'test/essentials/ci'
    ref: main
    file: 'build/alse/build-alse-strict.yml'

  - project: 'test/essentials/ci'
    ref: main
    file: 'build/windows/build-windows-strict.yml'

  - local: /.gitlab/integration-test-astra.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "trigger-install-windows"
        when: never
      - when: always
  - local: /.gitlab/doxygen.yml
  - local: /.gitlab/install.yml





