---
stages:
  - build
  - test
  - deploy

include:
  - project: "developers/v2/libs/essentials/ci"
    ref: main
    file:
      - 'linux/conan.yml'
      - 'utils/variables.yml'

local_variables:
  extends: .variables_core_job
  script:
    - !reference [.svariables, conan_project_name]

build:alse:
  stage: build
  extends: .build_extend
  artifacts:
    paths:
      - build/Release

test:alse:
  stage: test
  allow_failure: true
  extends: .tests_catch2_extend

publish:alse:
  stage: deploy
  extends: .publish_extend

deploy:alse:
  stage: deploy
  extends: .deploy_library_extend