variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0

stages: 
  - build
  - publish

linux:
  stage: build
  tags: [alse]
  script: 
    - echo "$(conan inspect . | grep "name. (\S+)")"
    - conan install . -b "missing"
    - cmake . -B target -G Ninja -DCMAKE_TOOLCHAIN_FILE=./build/Release/generators/conan_toolchain.cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
    - cmake --build target
    - cmake --install target --prefix target/export

  artifacts:
    paths:
      - target/export
    expire_in: 1 hour

windows:
  stage: build
  tags: [windows-arch]
  allow_failure: true
  script:
    - echo "Building Windows"
    - exit 1

  artifacts:
    paths:
      - target
    expire_in: 1 hour

publish:
  stage: publish
  tags: [alse]
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: manual
  needs:
    - job: linux
      artifacts: false
    - job: windows
      artifacts: false
  script:
    - echo "Publishing to conan repo"
    - conan create . -b "missing"
    - conan upload "$(conan inspect . | grep "name. (\S+)")" -r "radar" -c
    - echo "Done"

