variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 100
  PKG_VER: 0.0.0  

stages:
  - build
  - integration-test
  - install
  - documentation
  
include:
  - local: /.gitlab/build-astra.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "trigger"
        when: never
      - when: always
  - local: /.gitlab/build-windows.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "trigger"
        when: never
      - when: always
  - local: /.gitlab/integration-test-astra.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "trigger"
        when: never
      - when: always
  - local: /.gitlab/doxygen.yml
  - local: /.gitlab/install.yml
    rules:
      - when:  
        on-success: build astra




