[package]
name = "leaf"
version = "0.4.2"
authors = ["whs31 <whs31@github.io>"]
description = "Core library of simulator namespace and beyond"

[dependencies]
cmake = { version = "0.1.3", distribution = "sources" }
fmt = { version = "10.1.1", distribution = "static" }
spdlog = { version = "1.13.0", distribution = "static" }
magicenum = { version = "0.9.5", distribution = "static" }