[this]
name = "leaf"
version = "0.4.4"
authors = [
    "whs31 <whs31@github.io>"
]
description = "Coreutils library for C++"
license = "MIT"

[needs]
cmake = "^0.1.3"
fmt = "^10.1.1"
spdlog = "^1.13.0"
magicenum = "^0.9.5"