[this]
name = "leaf"
version = "0.4.55"
authors = [
    "whs31 <whs31@github.io>"
]
description = "Coreutils library for C++"
license = "MIT"

[needs]
cmake = "^0.1.3@static"
fmt = "^10.1.1@static"
spdlog = "^1.13.0@static"
magicenum = "^0.9.5@static"