name: gh-pages

on:
  push:
    branches:
      - main
      - master
      - release/*
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install --no-install-recommends git python3 python3-pip doxygen
          sudo -H pip3 install --upgrade poxy

      - name: Generate docs
        run: |
          git fetch origin main:refs/remotes/origin/main --tags --force
          git remote set-head origin -a
          git checkout main
          git pull --force
          cd .doc
          poxy 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.doc/html
